name: Deploy pkgdown site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        install.packages('devtools')
        devtools::install_deps(dependencies = TRUE)

    - name: Install pkgdown
      run: install.packages('pkgdown')

    - name: Build pkgdown site
      run: |
        Rscript -e 'pkgdown::build_site()'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
